apiVersion: v2
name: Az-CertManagerIssuer
description: CertManager is an automated certificate manager for Kubernetes.
type: application
version: 0.3.0 #chart version
appVersion: "1.0.1" #your app version (used as an image tag)
