# Checks for broken links

name: Broken Link Checker

on:
  schedule:
    - cron: 0 0 1 * * # run monthly
  repository_dispatch: # run manually
    types: [check-link]

jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Repo - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
      - name: Helper - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with: 
          TARGET: https://azure.github.io/AKS-Construction/
          RECURSIVE: false
      - name: Helper (preview) - Broken Link Check
        uses: technote-space/broken-link-checker-action@v2
        with: 
          TARGET: https://azure.github.io/AKS-Construction/?feature=defender
          RECURSIVE: false
