name: Test-Java App Deploy

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency: ci-${{ github.ref }}
jobs:

  deploy-java-app-kvssl:
    uses: azure/aks-construction/.github/workflows/AppDeploy_SelfSignedKV.yml@gb-privatelink-cicd
    with:
      RG: Automation-Actions-AksDeployCI
      AKSNAME: aks-Byo
      DNSDOMAIN: azdemo.co.uk
      DNSRG: domainssl
      DNSRECORDNAME: openjdk-demo
      AKVNAME: kv-Byo
      AGNAME: agw-Byo
      APPNAME: openjdk-kvssl
      FRONTENDCERTNAME: openjdk-kvssl-fe
      MINIHELMBRANCH: main

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
