# Workflow is for testing reusable workflows to expedite the developer inner loop.

name: Test Harness for Reusable workflows

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: "azurecirgs"
        type: environment

concurrency: ci-${{ github.ref }}

env:
  RG: "Automation-Actions-AksDeployCI"

jobs:
  ReusableWF:
    runs-on: ubuntu-latest
    outputs:
      RG: ${{ env.RG }}
      Uninstall: ${{ github.event.inputs.doSmokeTestUninstall }}

    steps:
      - name: Dummy step
        run: echo "Resuable workflows can't be directly passed ENV/INPUTS (yet)"

  Troubleshoot:
    needs: [ReusableWF]
    uses: ./.github/workflows/AksTroubleshooting.yml
    if: always()
    with:
      environment: ${{ github.event.inputs.environment }}
      RG: ${{ needs.ReusableWF.outputs.RG }} #Automation-Actions-AksDeployCI #'${{ env.RG }}' There seems to be an issue passing Env variables in reusable workflows
      AKSNAME: 'aks-PrvUKW'
      AGNAME: 'appgw-PrvUKW'
      LANAME: 'log-PrvUKW'
      LAWGUID: '3c28e99b-e4cd-4e6a-99e6-ace8aa44b754'
      USERUNCMD: true
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}