name: Test-Java App Deploy

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency: ci-${{ github.ref }}

env:
  RG: "Automation-Actions-AksDeployCI"


jobs:
  checkenv:
    runs-on: [ubuntu-latest]
    steps:
      - run: echo ${{fromjson(env)}}
      
  deploy-java-app-certmgr:
    uses: azure/aks-construction/.github/workflows/AppDeploy_CertManagerd.yml@gb-privatelink-cicd
    with:
      RG: $RG
      AKSNAME: aks-Byo
      DNSDOMAIN: azdemo.co.uk
      DNSRG: domainssl
      DNSRECORDNAME: openjdk-demo
      AKVNAME: kv-Byo
      AGNAME: agw-Byo
      APPNAME: openjdk-kvssl
      #MINIHELMBRANCH: main

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  deploy-java-app-kvssl:
    needs: [deploy-java-app-certmgr]
    uses: azure/aks-construction/.github/workflows/AppDeploy_SelfSignedKV.yml@gb-privatelink-cicd
    with:
      RG: ${RG}
      AKSNAME: aks-Byo
      DNSDOMAIN: azdemo.co.uk
      DNSRG: domainssl
      DNSRECORDNAME: openjdk-demo
      AKVNAME: kv-Byo
      AGNAME: agw-Byo
      APPNAME: openjdk-kvssl
      FRONTENDCERTNAME: openjdk-kvssl-fe
      MINIHELMBRANCH: main

    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
